import React from 'react';

const PolicyPage = () => {
  return (
    <div className="container mx-auto px-4 py-8">
      <h1 className="text-3xl font-bold mb-6">Policies</h1>

      {/* Terms of Use Section */}
      <section className="mb-8">
        <h2 className="text-2xl font-semibold mb-4">Terms of Use</h2>
        <div className="space-y-4">
          <p>
            This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
          </p>
          <p>
            This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of domain name techbuddyspace.xyz ('Website'), including the related mobile site and mobile application (hereinafter referred to as 'Platform').
          </p>
          {/* Add more content as needed */}
        </div>
      </section>

      {/* Privacy Policy Section */}
      <section className="mb-8">
        <h2 className="text-2xl font-semibold mb-4">Privacy Policy</h2>
        <div className="space-y-4">
          <p>
            This Privacy Policy describes how Tech Buddy Space and its affiliates (collectively "Tech Buddy Space, we, our, us") collect, use, share, protect or otherwise process your information/ personal data through our website techbuddyspace.xyz (hereinafter referred to as Platform). Please note that you may be able to browse certain sections of the Platform without registering with us.
          </p>
          <p>
            We do not offer any product/service under this Platform outside India and your personal data will primarily be stored and processed in India. By visiting this Platform, providing your information or availing any product/service offered on the Platform, you expressly agree to be bound by the terms and conditions of this Privacy Policy, the Terms of Use and the applicable service/product terms and conditions, and agree to be governed by the laws of India including but not limited to the laws applicable to data protection and privacy. If you do not agree please do not use or access our Platform.
          </p>
          {/* Add more content as needed */}
        </div>
      </section>

      {/* Refund and Cancellation Policy Section */}
      <section className="mb-8">
        <h2 className="text-2xl font-semibold mb-4">Refund and Cancellation Policy</h2>
        <div className="space-y-4">
          <p>
            This refund and cancellation policy outlines how you can cancel or seek a refund for a product / service that you have purchased through the Platform. Under this policy:
          </p>
          <ul className="list-disc pl-6">
            <li>
              Cancellations will only be considered if the request is made within 1 day of placing the order. However, cancellation requests may not be entertained if the orders have been communicated to such sellers / merchant(s) listed on the Platform and they have initiated the process of shipping them, or the product is out for delivery. In such an event, you may choose to reject the product at the doorstep.
            </li>
            <li>
              Tech Buddy Space does not accept cancellation requests for perishable items like flowers, eatables, etc. However, the refund / replacement can be made if the user establishes that the quality of the product delivered is not good.
            </li>
            <li>
              In case of receipt of damaged or defective items, please report to our customer service team. The request would be entertained once the seller/ merchant listed on the Platform, has checked and determined the same at its own end. This should be reported within 1 day of receipt of products. In case you feel that the product received is not as shown on the site or as per your expectations, you must bring it to the notice of our customer service within 1 day of receiving the product. The customer service team after looking into your complaint will take an appropriate decision.
            </li>
            <li>
              In case of complaints regarding the products that come with a warranty from the manufacturers, please refer the issue to them.
            </li>
            <li>
              In case of any refunds approved by Tech Buddy Space, it will take 7 days for the refund to be processed to you.
            </li>
          </ul>
        </div>
      </section>
    </div>
  );
};

export default PolicyPage;